### ISSUE TITLE
globalInit()  -  No implementation found

### ISSUE THREAD

**Issue by dholiya** [cernekee/ics-openconnect#53]
2019-09-13 22:35:25.794 14913-15408/app.openconnect E/zygote: No implementation found for void org.infradead.libopenconnect.LibOpenConnect.globalInit() (tried Java_org_infradead_libopenconnect_LibOpenConnect_globalInit and Java_org_infradead_libopenconnect_LibOpenConnect_globalInit__)

2019-09-13 22:35:25.797 14913-15408/app.openconnect E/AndroidRuntime: FATAL EXCEPTION: OpenVPNManagementThread
Process: app.openconnect, PID: 14913

  java.lang.UnsatisfiedLinkError: No implementation found for void org.infradead.libopenconnect.LibOpenConnect.globalInit() (tried Java_org_infradead_libopenconnect_LibOpenConnect_globalInit and Java_org_infradead_libopenconnect_LibOpenConnect_globalInit__)
        at org.infradead.libopenconnect.LibOpenConnect.globalInit(Native Method)
        at org.infradead.libopenconnect.LibOpenConnect.<clinit>(LibOpenConnect.java:272)
        at app.openconnect.core.OpenConnectManagementThread.runVPN(OpenConnectManagementThread.java:701)
        at app.openconnect.core.OpenConnectManagementThread.run(OpenConnectManagementThread.java:282)
        at java.lang.Thread.run(Thread.java:764)

**Comment by giovanni-orb** [comment]
Has this ever been fixed?

**Comment by filizsenturk** [comment]
Are there any solutions for this error?
